version: '3.9'

services:
  db:
    image: postgres:12.8-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  app:
    build:
      context: '.'
    environment:
      DJANGO_SETTINGS_MODULE: 'avito.settings_docker'
    ports:
      - '8000:80'